# # Starter pipeline
# # Start with a minimal pipeline that you can customize to build and deploy your code.
# # Add steps that build, run tests, deploy, and more:
# # https://aka.ms/yaml

# trigger:
# - main

# pool:
#   vmImage: ubuntu-latest

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'


trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- task: TerraformTaskV2@2
  inputs:
    provider: 'aws'
    command: 'init'
    backendServiceAWS: 'azdo-aws-sc'
    backendAWSBucketName: 'aws-s3-bucket-test-state'
    backendAWSKey: '$(Build.Repository.Name).tfstate'

- task: TerraformTaskV2@2
  inputs:
    provider: 'aws'
    command: 'plan'
    environmentServiceNameAWS: 'azdo-aws-sc'

- task: TerraformTaskV2@2
  inputs:
    provider: 'aws'
    command: 'apply'
    environmentServiceNameAWS: 'azdo-aws-sc'